### PR TITLE
Added desktop notifications to Chrome extension

### PR DESCRIPTION
**Pull request by cdrini**
Added desktop notifications to the chrome extension when results are received (see #3 ). Here are some samples:

Notification from ProblemsList:
image
Clicking "View results" opens a new tab to the submission ("submission.jsp?submissionPK=...")
Clicking the notification brings focus to the marmoset tab if still open, else opens a new one.

Notification from SubmissionsList:
image
Clicking the notification brings focus to the marmoset tab if still open, else opens a new one.

### CODE REVIEW

**Comment by lishid** [comment]
Looks great!

I'm curious whether the notification shows up if you're already on the page, or does Chrome hide/prevent the notification if you're already on page.

Another thing I'm curious about is that it "brings focus to the marmoset tab if still open".
Does the notification work if you close the tab? I would think that once the tab closes, the async request is gone and therefore cannot trigger the notification to show up. Am I wrong?

Other than those, it's looking pretty nice. I'll pull it in a bit and give it a test run!

**Comment by cdrini** [comment]
Glad you like it!
Currently the notification will show up even if you're already on the page, but if you'd like, I don't think it would take me too long (5 lines?) to add that feature.

The case is if marmoset shows the notification, and the user closes marmoset *while* the notification is still being displayed. Relatively extreme edge case, to be honest, though.

**Comment by lishid** [comment]
I think it would be useful to prevent the notification if you're already looking at the page.

Another thing I was curious is whether Chrome lets you disable notifications somehow. If such is not the case, some might find it annoying for notifications to popup while they're working on other things, and we might want a settings page for disabling it.

**Comment by cdrini** [comment]
Ok, the notification will no longer show if you have the page open.

And chrome does have a setting to disable notifications:
image

I made sure the app works correctly if they are disabled.

(I *did* create an options page before finding this, though. In case that's ever useful, I have it saved as a branch on my fork: https://github.com/cdrini/MarmoUI/tree/optionsPage )

**Comment by cdrini** [comment]
P.S.
A quick way to test notifications is to type the following in the browser console when marmoset is open:
```javascript
setTimeout(function() {window.postMessage({type:"resultsNotification", notification:{}},"*")}, 1000)
```
It will just make a junk notification, though. Be sure to leave the marmoset tab/window before the timeout ends!

**Pull request merged**
